// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Ticket struct {
	ID          int64      `json:"id"`
	ReferenceNo string     `json:"reference_no"`
	Status      string     `json:"status"`
	UserID      *int64     `json:"user_id"`
	CreatedAt   *time.Time `json:"created_at"`
}
