// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClaimTicket(ctx context.Context, arg ClaimTicketParams) error
	DeleteTicket(ctx context.Context, referenceNo string) (sql.Result, error)
	GetAllTickets(ctx context.Context) ([]Ticket, error)
	GetTicketByRef(ctx context.Context, referenceNo string) (Ticket, error)
	InsertTIcket(ctx context.Context, arg InsertTIcketParams) error
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) error
}

var _ Querier = (*Queries)(nil)
