// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const claimTicket = `-- name: ClaimTicket :exec
UPDATE tickets SET status = ?, user_id = ? WHERE id = ?
`

type ClaimTicketParams struct {
	Status string `json:"status"`
	UserID *int64 `json:"user_id"`
	ID     int64  `json:"id"`
}

func (q *Queries) ClaimTicket(ctx context.Context, arg ClaimTicketParams) error {
	_, err := q.db.ExecContext(ctx, claimTicket, arg.Status, arg.UserID, arg.ID)
	return err
}

const deleteTicket = `-- name: DeleteTicket :execresult
DELETE FROM tickets WHERE reference_no = ?
`

func (q *Queries) DeleteTicket(ctx context.Context, referenceNo string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTicket, referenceNo)
}

const getAllTickets = `-- name: GetAllTickets :many
SELECT id, reference_no, status, user_id, created_at FROM tickets
`

func (q *Queries) GetAllTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getAllTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNo,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketByRef = `-- name: GetTicketByRef :one
SELECT id, reference_no, status, user_id, created_at FROM tickets WHERE reference_no = ? LIMIT 1
`

func (q *Queries) GetTicketByRef(ctx context.Context, referenceNo string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByRef, referenceNo)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ReferenceNo,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTIcket = `-- name: InsertTIcket :exec
INSERT INTO tickets (reference_no, status, user_id) VALUES (?, ?, ?)
`

type InsertTIcketParams struct {
	ReferenceNo string `json:"reference_no"`
	Status      string `json:"status"`
	UserID      *int64 `json:"user_id"`
}

func (q *Queries) InsertTIcket(ctx context.Context, arg InsertTIcketParams) error {
	_, err := q.db.ExecContext(ctx, insertTIcket, arg.ReferenceNo, arg.Status, arg.UserID)
	return err
}

const updateTicket = `-- name: UpdateTicket :exec
UPDATE tickets SET status = ? WHERE reference_no = ?
`

type UpdateTicketParams struct {
	Status      string `json:"status"`
	ReferenceNo string `json:"reference_no"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) error {
	_, err := q.db.ExecContext(ctx, updateTicket, arg.Status, arg.ReferenceNo)
	return err
}
