// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	FindUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
